# Generated by Django 3.1 on 2023-12-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('code', models.CharField(db_index=True, editable=False, max_length=256)),
                ('quota', models.IntegerField(default=1)),
                ('is_attended', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
