# Generated by Django 3.1 on 2023-12-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitee',
            old_name='message',
            new_name='message_from_bride',
        ),
        migrations.AddField(
            model_name='invitee',
            name='message_to_bride',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitee',
            name='deleted_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
