# Generated by Django 3.1 on 2023-12-05 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231205_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitee',
            name='message_from_bride',
        ),
        migrations.RemoveField(
            model_name='invitee',
            name='message_to_bride',
        ),
        migrations.AddField(
            model_name='invitee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MessageToBride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.invitee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
