# Generated by Django 3.1 on 2023-12-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231205_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='message_from_bride',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
