# Generated by Django 4.2.9 on 2024-04-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_love'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.invitee'),
        ),
    ]
