# Generated by Django 4.2.9 on 2024-04-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_friendgroup_invitee_friend_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.invitee'),
        ),
    ]
